### ISSUE TITLE
건의사항입니다.

### ISSUE THREAD

**Issue by smucon** [rabbitot/CCMS_V2#150]
그리드에서 C와 U, D 의 상태값이 남아있을때 True false 값을 반환해주는 공통 함수가 필요합니다.

이벤트 발생시 공통 함수호출로 데이터변경이 있을경우 수정중인 데이터 저장 다이얼로그를 띄울때 쓰고 싶습니다.

**Comment by rabbitot** [comment]
dataset.getStatInfo() 가 추가되었습니다.

getStatInfo = function(rtnType, statValue)
rtnType -> return 받고 싶은 값을 입력하면 됩니다. ex) boolean, index, count [미 입력시 boolean 값]
statValue -> 검색하고 싶은 상태값을 입력하면 됩니다. ex) C, U, D 또는 ['C', 'U'] ...
